### ISSUE TITLE
Xamarin.android

### ISSUE THREAD

**Issue by sagarmp02** [brminnick/FacialRecognitionLogin#1]
i need to implement auto capture image in xamarin.android. please
![lrfit](https://user-images.githubusercontent.com/37401688/37518750-7c821a7e-293c-11e8-8d66-9dfb3b17a1c3.png)
 help me

**Comment by brminnick** [comment]
Closing because it is not an issue with the application

**Comment by VisakhRaman** [comment]
Hi, 
I understand this isn't an issue with your project, but is this possible with Xamarin Android ?
I referred to this [post](https://blog.xamarin.com/adding-face-tracking-live-recognition-android-app/) but I'm getting runtime errors. 

Can you advice on how I should proceed?
