### ISSUE TITLE
FaceApiClient API call is always returning "Not Found"

### ISSUE THREAD

**Issue by BoobalanK** [brminnick/FacialRecognitionLogin#5]
i created an trail account using microsoft account for 7 days. I got the API key as well

API Key: 60cd5dd26082443a861ebd4013f238a4
Endpoint: https://westcentralus.api.cognitive.microsoft.com/face/v1.0

The above it replaces in the AzureConstants class.

I tried the source code and deployed the solution in an iPAD. Every time i tried to take photo and after completing the photo capture the FaceApiClient is returning this error message **Operation returned an invalid status code "Not found"**

Please can you assist me on this?

**Comment by sawankumarbundelkhandi** [comment]
@BoobalanK, You should use [https://westcentralus.api.cognitive.microsoft.com](https://westcentralus.api.cognitive.microsoft.com/face/v1.0) as Endpoint.

Please look at this issue by @brminnick - https://github.com/Azure/azure-sdk-for-net/issues/4633
